### ISSUE TITLE
Split exercises and solutions

### ISSUE THREAD

**Issue by robertoschiavone** [michaelgutmann/ml-pen-and-paper-exercises#6]
When going through the exercises I find almost impossible not to glance at the solutions, since they are presented right after the questions.

Are you open to consider an alternate version of the pdf where the solutions are at the end (either after each chapter or after all of them)?

I could work on it and submit a PR.

**Comment by chensong1995** [comment]
I believe there is a [flag](https://github.com/michaelgutmann/ml-pen-and-paper-exercises/blob/master/main.tex#L43) for this.

**Comment by michaelgutmann** [comment]
Yes, the [flag](https://github.com/michaelgutmann/ml-pen-and-paper-exercises/blob/master/main.tex#L43) allows you to compile a document without the solutions. See the explanation [here](https://github.com/michaelgutmann/ml-pen-and-paper-exercises/#usage).
